language: cpp
compiler:
#  - gcc
  - clang
env:
  - CFLAGS=--coverage CXXFLAGS=--coverage
before_install:
  - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 597DAA6A 11784C4C
  - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe'
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/makson96/desurium-travis/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install gcc-multilib libnotify-dev libboost1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libgtest-dev libwxgtk3.0-dev clang-3.4
  - export CC=clang-3.4
  - export CXX=clang++-3.4
  - clang -v
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake . -DBUILD_CEF=off -DDEBUG=on -DWITH_GTEST=ON -DBUILD_TESTS=ON
  - make -j4
  - ctest --output-on-failure .
after_success:
  - coveralls --exclude third_party --exclude src/tests --exclude breakpad-prefix --exclude gtest-prefix --exclude fetch_cef-prefix/src/fetch_cef/tests --exclude fetch_cef-prefix/src/fetch_cef/libcef --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
notifications:
  irc:
    channels:
      - "irc.freenode.org#desura"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change
    skip_join: true 
