language: cpp
compiler:
  - gcc
  - clang
env:
  - CFLAGS=--coverage CXXFLAGS=--coverage
before_install:
  - sudo add-apt-repository --yes ppa:makson96/desurium-travis
  - sudo apt-get update
  - sudo apt-get install -qq libnotify-dev libboost1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libgtest-dev libwxgtk3.0-dev wx-common clang-3.4 cmake gcc-4.8 g++-4.8 gcc-4.8-multilib libv8-dev
  - if [ $CC == "clang" ]; then export CC=clang-3.4 && export CXX=clang++-3.4; fi
  - if [ $CC == "gcc" ]; then export CC=gcc-4.8 && export CXX=g++-4.8; fi
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake . -DBUILD_CEF=off -DDEBUG=on -DWITH_GTEST=ON -DBUILD_TESTS=ON
  - make
  - ctest --output-on-failure .
after_success:
  - coveralls --exclude third_party --exclude src/tests --exclude breakpad-prefix --exclude gtest-prefix --exclude fetch_cef-prefix/src/fetch_cef/tests --exclude fetch_cef-prefix/src/fetch_cef/libcef --exclude CMakeFiles --exclude-pattern 'CMake[^\.]*\.c(?:pp)?' --exclude-pattern '[^\.]*\.h' > /dev/null
notifications:
  irc:
    channels:
      - "irc.freenode.org#desura"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change
    skip_join: true 
